---
collections:
  - name: cisco.ios
  - name: arista.eos
  - name: ansible.netcommon
  - name: community.postgresql
  - name: community.general
  - name: redhat.rhel_idm
  - name: netbox.netbox
  - name: containers.podman
  - name: ansible.controller
